spring.application.name=airLineProject
spring.datasource.url=jdbc:postgresql://localhost:5432/airline_db
spring.datasource.username=postgres
spring.datasource.password=Mohjad04--

spring.jpa.hibernate.ddl-auto=validate
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

jwt.secret=9b3c1a7f0e2d4c6b8a1f3d5e7c9b0a2d9b3c1a7f0e2d4c6b8a1f3d5e7c9b0a2d
jwt.expMinutes=60

